name: SDKs (macOS)
on:
  #pull_request:
  #schedule:
    #- cron: '0 21 * * *'
  push:
    branches: '*'
jobs:
  build-toolchain:
    # The macos-14 GH Runner is ARM, which cannot run the Android emulator
    runs-on: macos-13
    timeout-minutes: 1000
    strategy:
      matrix:
        swift_branch: ['release/5.10']
        #swift_branch: ['release/5.10', 'release/6.0', 'main']
      fail-fast: false
    steps:
      - name: Install Tools
        run: brew install tree

      - name: "Install NDK"
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27
          add-to-path: false

      - name: Set NDK
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Check NDK
        run: |
          echo "NDK: ${ANDROID_NDK_HOME}"
          ls ${ANDROID_NDK_HOME}

      - name: Install Toolchain
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.1"

      - name: Set Swift Toolchain
        run: |
          swift --version
          which swift
          echo "TOOLCHAIN=$(dirname $(dirname $(which swift)))" >> $GITHUB_ENV

      - name: Check Swift Toolchain
        run: |
          echo "TOOLCHAIN: ${TOOLCHAIN}"
          ${TOOLCHAIN}/bin/swift --version

      - name: Fetch Android SDK
        run: |
          wget https://github.com/finagolfin/swift-android-sdk/releases/download/5.10/swift-5.10-android-24-sdk.tar.xz
          tar xf swift-5.10-android-24-sdk.tar.xz
          ls swift-5.10-android-24-sdk


