name: SDKs (macOS)
on:
  #pull_request:
  #schedule:
    #- cron: '0 21 * * *'
  push:
    branches: '*'
jobs:
  build-toolchain:
    # The macos-14 GH Runner is ARM, which cannot run the Android emulator
    runs-on: macos-13
    timeout-minutes: 1000
    strategy:
      matrix:
        swift_branch: ['release/5.10']
        #swift_branch: ['release/5.10', 'release/6.0', 'main']
      fail-fast: false
    steps:
      - name: Install Tools
        run: brew install tree

      - name: Install Toolchain
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.1"

      - name: Check Swift
        run: |
          swift --version
          which swift
          ls ${HOME}/hostedtoolcache/swift-macOS/5.10.1/x64/usr
          tree ${HOME}/hostedtoolcache/swift-macOS/5.10.1/x64
          echo "TOOLCHAIN=$(dirname $(dirname $(which swift)))" >> $GITHUB_ENV
          echo "TOOLCHAIN: ${TOOLCHAIN}"
          ${TOOLCHAIN}/bin/swift --version

      - name: Fetch Android SDK
        run: |
          wget https://github.com/finagolfin/swift-android-sdk/releases/download/5.10/swift-5.10-android-24-sdk.tar.xz
          tar xf swift-5.10-android-24-sdk.tar.xz
          ls swift-5.10-android-24-sdk


