name: SDKs (macOS)
on:
  #pull_request:
  #schedule:
    #- cron: '0 21 * * *'
  push:
    branches: '*'
jobs:
  build-toolchain:
    # The macos-14 GH Runner is ARM, which cannot run the Android emulator
    runs-on: macos-13
    timeout-minutes: 1000
    strategy:
      matrix:
        swift_branch: ['release/5.10']
        #swift_branch: ['release/5.10', 'release/6.0', 'main']
      fail-fast: false
    steps:
      - name: Install Toolchain
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.1"

      - name: Check Swift
        run: swift --version

      - name: Check Toolchain
        run: ls /Library/Developer/Toolchains

